#!/bin/bash

# Ship your change!
#
# Commit the latest changes, get the latest main and merge it, run tests and linter
# and, if all is OK, merge your changes to main and push to origin for deploy.

. scripts/common.sh

sha=$(git rev-parse HEAD)
branch=$(git rev-parse --abbrev-ref HEAD)
tmp_branch="merge_test_$sha"

msg "Committing changes"
commit

set -e

msg "Switching to main"
git checkout main

msg "Getting latest main"
git pull

msg "Switching to integration branch: $tmp_branch"
git checkout -b $tmp_branch

msg "Merging changes from $branch"
git merge $branch

lint

msg "Tests OK, deleting integration branch: $tmp_branch"
git checkout main
git branch -D $tmp_branch

msg "Merging your changes to main"
git merge $branch

msg "Deploying"
yarn run deploy

# Commit can fail for no files to add, this is fine.
set +e
commit
set -e

msg "Pushing main to git server"
git push origin main

msg "Deleting feature branch"
git branch -D $branch

msg "Nice work!"
